### ISSUE TITLE
Multibyte characters can't be saved correctly.

### ISSUE THREAD

**Issue by ngs** [sidorares/nodejs-mysql-native#14]
Hello there,

There is a multibyte chacactors problem in 'nodejs-mysql-native'.

See this test fails ngs/nodejs-mysql-native@24a3a89d4add3314eeffa1544ed86a2e91e6153f

When tried to insert records with multibyte values like the below, multibyte charactors cannot be saved correctly.
https://gist.github.com/839181#file_test_mysql_native.js

**Comment by sidorares** [comment]
thanks) closing issue
