### ISSUE TITLE
'end' emitted twice for execute

### ISSUE THREAD

**Issue by halldor** [sidorares/nodejs-mysql-native#16]
The 'end' callback is triggered twice for execute statements. A simple demo:

```
var db = require('mysql-native').createTCPClient('127.0.0.1');

db.auth('test', 'testuser', 'testpass').on('authorized', function(status) {
    console.log('connect.');
});

db.prepare('SELECT ?').on('end', function() {
    console.log('end prepare');
});

db.execute('SELECT ?', [1]).on('row', function(row) {
    console.log(row);
}).on('end', function(cmd) {
    console.log('end execute');
});

db.close();
```

Expected output:
    connect.
    end prepare
    { '0': '1' }
    end execute

Actual output:
    connect.
    end prepare
    { '0': '1' }
    end execute
    end execute

This did not happen with the version that's current on npm but happens with the trunk version.

**Comment by chrisdew** [comment]
Yes, I see this too.  It plays havoc with sequenced queries, as the population doubles on each generation.

**Comment by halldor** [comment]
That's exactly what I was trying to use the end event for. After skimming through the code for the prepare statement real quick I couldn't see anything that should cause this so I decided to use the result event instead.

You could try using that.

**Comment by chrisdew** [comment]
Thanks, that's just what I need.

**Comment by chrisdew** [comment]
Does the 'result' fire after all the rows, or will I still have an issue with 'end' firing twice?

**Comment by halldor** [comment]
The 'result' event fires once. Either after the command is successfully executed or, if there are any fields (i.e. there might be rows you're fetching), after all the 'row' events.
