### ISSUE TITLE
Prepared_stmt_count exhausted by trivial test case.

### ISSUE THREAD

**Issue by chrisdew** [sidorares/nodejs-mysql-native#19]
Hi Sidorares,

When the code below is run on node@v0.2.6, mysql-native@0.4.1, "mysql  Ver 14.14 Distrib 5.1.41, for debian-linux-gnu (x86_64) using readline 6.1" I encounter the following bug:

After 8k executions of "fooFindOrCreate" I get the error: {"field_count":255,"errno":1461,"message":"Can't create more than max_prepared_stmt_count statements (current value: 16382)"}

If I watch the value of Prepared_stmt_count in MySQL, using "mysqladmin extended-status" I see the value of Prepared_stmt_count increase by two every time fooFindOrCreate is invoked.

Does any else experience a similar problem?  Is this a bug, or am I using the API incorrectly?

The minimal source below is sufficient to recreate the issue, though you'll need to create a database and table with the required columns and at least one matching row.

All the best,

Chris.

P.S. If there's anything more I can do to help resolve this, please let me know.
P.P.S. You can work-around this problem by reconnecting after every few queries, but this is not a longterm solution.

<pre>
#!/usr/local/bin/node

var sys = require('sys');
var net = require('net');
var my = require('mysql-native')

var db = my.createTCPClient("127.0.0.1", 3306);
db.auto_prepare = true;
db.auth("dbname", "username", "password");
db.addListener('connect', function() {
    console.log("connection connected");
}); 
db.addListener('end', function() {
    console.log("connection ended");
}); 
db.addListener('error', function() {
    console.log("connection error");
});
db.addListener('close', function() {
    console.log("connection closing");
});

setInterval(function() { fooFindOrCreate("5421"); }, 10);

function fooFindOrCreate(callsign) {
    var sql = "SELECT foo_ptr_id "
            + "FROM resource "
            + "WHERE callsign = ? "
            + ";"
            ;
    console.log("sql", sql, callsign);
    //system.exit(1);
    var query = db.execute(sql, [callsign]) ; 
    var foo_id = false;
    query.addListener('row', function(row) {
        console.log("row: " + JSON.stringify(row));
        foo_id = row[0];
    });
    query.addListener('end', function() {
        if (foo_id) {
            console.log("query completed, foo_id: " + foo_id);
        } else {
            console.log("query returned no results");
        }
    });
    query.addListener('error', function(err) {
        console.log("query returned an error", err);
    });
}

</pre>

**Comment by chrisdew** [comment]
I can confirm that using the latest code in master fixes the issue.  Will there be a new stable package released?

**Comment by sidorares** [comment]
I'll try to investigate the problem, thanks for report. I'd like to see at what point it was fixed.

I don't use the library actively at the moment, all changes a driven outside fith bug reports and feature requests. I also apply pull requests from time to time.

If you need any major feature feel free to express your interest

**Comment by chrisdew** [comment]
Thanks for your reply.  I'll be creating a mysql-native-prerelease npm package @0.4.2 which I'll use as a fix until the real 0.4.2 (or later) is released.  Is there a less hacky way of doing this?

**Comment by sidorares** [comment]
please add code to your example which will create all required temporarily tables, I'll add your code to the tests and publish as 0.4.2

**Comment by chrisdew** [comment]
Here's a modified version of the code which creates and populates a temporary table and still exhibits the same problem.  It should help in bisecting the problem.

All the best,

Chris.

<pre>
#!/usr/local/bin/node

// Some code to illustrate a problem with Prepared_stmt_count being exhausted
// in mysql-native@0.4.1

// See: https://github.com/sidorares/nodejs-mysql-native/issues/closed#issue/19

// N.B. This is very hacky, if I didn't mind adding dependencies here 
// (which I do) a would use Step, or similar, to sequence to the creation, 
// insertion and select queries.

var sys = require('sys');  
var net = require('net');  
var my = require('mysql-native')

var db = my.createTCPClient("127.0.0.1", 3306);  
db.auto_prepare = true;  
db.auth("dbname", "username", "password");  
db.addListener('connect', function() {  
    console.log("connection connected");
    create(function() {
        insert(function() {
            setInterval(function() {
                fooFindOrCreate("5421");
            }, 10); 
        });
    }); 
}); 
db.addListener('end', function() {  
    console.log("connection ended");
}); 
db.addListener('error', function() {  
    console.log("connection error");
});
db.addListener('close', function() {  
    console.log("connection closing");
});
               
function create(callback) {  
    console.log("creating test table");
    var sql = "CREATE TEMPORARY TABLE test_table ("
            + "  id int(11) NOT NULL "
            + ", callsign varchar(48) NOT NULL "
            + ") ;"
    var query = db.execute(sql);
    query.addListener('end', function() {
        console.log("query completed", sql);
        callback();
    });
    query.addListener('error', function(err) {
        console.log("query returned an error", sql, JSON.stringify(err));
    });
}

function insert(callback) {  
    console.log("inserting test row");
    var sql = "INSERT INTO test_table VALUES (40893840,'5421');"
    var query = db.execute(sql);
    query.addListener('end', function() {
        console.log("query completed", sql);
        callback();
    });
    query.addListener('error', function(err) {
        console.log("query returned an error", sql, JSON.stringify(err));
    });
}

function fooFindOrCreate(callsign) {  
    var sql = "SELECT id "
            + "FROM test_table "
            + "WHERE callsign = ? "
            + ";"
            ;
    console.log("sql", sql, callsign);
    //system.exit(1);
    var query = db.execute(sql, [callsign]) ; 
    var id = false;
    query.addListener('row', function(row) {
        console.log("row: " + JSON.stringify(row));
        id = row[0];
    });
    query.addListener('end', function() {
        if (id) {
            console.log("query completed, id: " + id);
        } else {
            console.log("query returned no results");
        }
    });
    query.addListener('error', function(err) {
        console.log("query returned an error", JSON.stringify(err));
    });
}
</pre>
