### ISSUE TITLE
NULL use, unicode fails

### ISSUE THREAD

**Issue by rdzar** [sidorares/nodejs-mysql-native#2]
On the table structure you can assign default values, if I use NULL as default and there is some row filled with 'NULL', the query function fails in fetching the fields after the NULL field.

As you can see:
 19 Jun 18:29:11 - [ '2D' (varchar)
  , '1,2,3,4,5,6,7' (set)
  , '[{"device":"2A","action":"off","timer":5}]' (mediumtext)
  , 1 (tinyint)
  , 0 (tinyint)
  , 0 (smallint)
  , 0 (smallint)
  ]

19 Jun 18:29:11 - [ '2D' (varchar)
  , '1,2,3,4,5,6,7' (set)
  , '\u00011\u00011\u00041800\u00041830' (... fails, because mediumtext is filled with NULL)
  ]

Temp fix: fill it with an empty string, but I can imagine that some people use NULL frequently, so fixing it would be nice anyway :-)

**Comment by sidorares** [comment]
fixed in http://github.com/sidorares/nodejs-mysql-native/commit/ab1664b97aaa1f71943068158155b513a8f71435
