### ISSUE TITLE
'result' object no longer includes 'insert_id' (in master, regression since 0.4.1?)

### ISSUE THREAD

**Issue by chrisdew** [sidorares/nodejs-mysql-native#20]
In mysql-native@0.4.1 there is an 'insert_id' property on the 'result' object which is given as the first parameter to the 'end' listener of a query.

In mysql-native master there is no such parameter on the result object.

Has the API changed, or is this a bug?

**Comment by sidorares** [comment]
it looks like API has changed, you can now receive result in 'result' event

**Comment by chrisdew** [comment]
Thanks, that's just what I need.
