### ISSUE TITLE
MySQL DATETIME fields are 'plus one month'.

### ISSUE THREAD

**Issue by chrisdew** [sidorares/nodejs-mysql-native#21]
This bug is present in my recent fork, but I haven't confirmed it in master here,

MySQL DATETIME fields become Javascript Dates, which are one month in advance of the value in the database.

This looks like a trivial bug related to Javascript's zero-based months.

If someone can point me at the code which makes the Javascript Dates, I'll go and fix it.

All the best,

Chris.

**Comment by sidorares** [comment]
it's in serializers/reader.js - unpackBinaryDateTime

**Comment by chrisdew** [comment]
Thanks, on it now.

**Comment by sidorares** [comment]
A good chance to try https://github.com/blog/844-forking-with-the-edit-button https://github.com/blog/843-the-merge-button :)

**Comment by chrisdew** [comment]
Sorry, I didn't try forking-with-edit-button, as a need my own fork to produce the mysql-native-prerelease package which we use.
