### ISSUE TITLE
when i use pool  console logs  and then break  

### ISSUE THREAD

**Issue by faylai** [sidorares/nodejs-mysql-native#26]
..........................
queue event 0
waiters: true
queue event 0
waiters: true
queue event 0
waiters: true
queue event 0
waiters: true
queue event 0
waiters: true
queue event 0
waiters: true
queue event 0
waiters: true

buffer.js:236
  if (!isFinite(offset)) {
       ^
undefined

**Comment by sidorares** [comment]
I'm rewriting current pool completely at the moment. About to release it in a couple of days
