### ISSUE TITLE
BIGINT values are truncated to 32 bits.

### ISSUE THREAD

**Issue by chrisdew** [sidorares/nodejs-mysql-native#43]
I have a database with BIGINT fields (millisecond timestamps).  Writing these fields works fine, but reading them results in the values being truncated to 32 bits.

e.g. 1313482901000 is read as 3517875720

Thanks,

Chris.

**Comment by sidorares** [comment]
do you read them from binary row (eg `execute` or `query` ?) Could you provide trivial test? ( I need to check what is the code for BIGINT - unpacking is done here https://github.com/sidorares/nodejs-mysql-native/blob/master/lib/mysql-native/serializers/reader.js#L125 from https://github.com/sidorares/nodejs-mysql-native/blob/master/lib/mysql-native/commands/execute.js#L176 )

**Comment by chrisdew** [comment]
I'm using execute.  I'll prepare a minimal example later today / early tomorrow, once I've finished with meetings.

DBCEE.prototype.runSql = function(sql, args, callback) {
  console.log('runSql', sql, args);
  var query = this.db_conn.db.execute(sql, args);
  query.on('result', function(result) { callback(null, result); });
  query.on('error', function(err) { callback(err); });
}

The behaviour is the same in different queries, so the actual SQL seems to be unimportant.

Thanks,

Chris.

**Comment by sidorares** [comment]
thanks, I'll take a look tonight

**Comment by sidorares** [comment]
BIGINT has type=8 ( MYSQL_TYPE_LONGLONG ) and SMALLINT - 2 ( MYSQL_TYPE_SHORT )

the MYSQL_TYPE_LONGLONG deserealisation seems to work fine ( only for signed though ) The problem in you case was that 2 bytes from SMALLINT data were neither read nor skipped from stream. I added a line for SMALLINT deserealisation, please check your test

**Comment by chrisdew** [comment]
Thanks, I'll checkout and test the latest version.

**Comment by chrisdew** [comment]
Yes, I can confirm that you have fixed both issues (which affected mysql-native@0.4.2).  

(Apologies, I should have done an npm update before submitting issues.) 

Thanks for your quick work, it's much appreciated.

Chris.

**Comment by sidorares** [comment]
you're welcome)

I'm planning big update which potentially can break API. Not sure who is actually using driver in the production (I don't), I'd like to hear any feedback.

Main changes:
- 'autoprepare' option obsolete (they are always auto-prepared unless you call prepare+execute with statement integer handle)
- if there is last callback parameter in the query or execute then all rows are buffered and rows array is passed as parameter to callback after each statement finished (could happen more then once in multi-statement query)
  otherwise you need to have on('row') handlers to process data.
- 'row as hash' option obsolete
  I think (not sure) that in the case where 'result' callback supplied rows are stored as hash indexed by field name.
  on('row') handler on the other hand gives you array of values
- internal pool and client creation API changed:
    var mysql = require('mysql-native');
    var client = mysql.createClient({ user: 'root', port: 3306, database: 'test'}); // creates client and adds one connection
    client.addConnection(); // adds connection, same link as above - localhost:3306
    client.addConnection({ host: replica1 });
    client.addConnection({ host: replica2 }); // root@replica1:3306
- auto-reconnection on unknown disconnect 
- queue control
    client.urgent().query('select sleep 0.1');      // puts command in front of the queue
    client.urgent(10).query('select sleep 0.1');  // puts command in front of the queue, but after commands older then 10 ms
  
    client.query('select sleep 0.2')
    client.query('select 1').expire(50);  // fire 'expire' event in the case command did not queue in 50ms, don't send it to server
- (not sure)  use query instead of execute in the case there is no parameters. Maybe completely remove execute? 
  
    client = mysql.createClient(params);
    client.query('select 1+1', function(result) {} ); // query command, result buffered
    client.query('select \* from data where page < ?', [10]); // execute, rows not buffered
    client.query('select 1+1', [], function(result) {} ); // execute
  
     client.query('select 1+1', [],  
      {
           field: someFieldHandler,
           row:  function(row) { 
                 //
           },
           eos: endOfStatementHandler
           end: endOfCommandHandler          // list of handlers, similar to chain of on('eventname')
      }); 

What do you think?

**Comment by chrisdew** [comment]
We ( http://www.thorcom.co.uk and http://www.xlocate.net ) are using nodejs-mysql-native in production.  (v0.4.2)

This all looks good.  Will development be done in a separate branch and with at least a higher minor version number?

Autoreconnection - this would allow me to remove my 'persistent_db' module.  Can  we have events on disconnect and (re)connection please and (redundantly) a function to query the current state of the connection?  An option to throttle reconnection?  Exponential backoff?

Can a reconnect timeout be set so that if a query would fail because of a failed connection, it doesn't error if the connection immediately (configurable ~5s?) comes back up.  (If I ever need to do a mysql restart, I'd prefer the http requests which are waiting on query results to hang for a few seconds, rather than error.  Other use cases exist.)

Would auto-reconnection be better implemented as a separate module which mysql-native would use instead of socket.connect?  I already use my own autoreconnecting tcp connection module - such a module (if done nicely) would be useful to many projects.  (I'm not happy with the design of my auto-reconnector.)  I'd be happy to redesign and publish my auto reconnector (if useful).

Callbacks - can they have the form function(err, result) to be consistent with the rest of NodeJS?  (I already wrap up queries so that they do (err, result) callbacks.)

Queue control - Not something I need, yet.

I'm very keen on keeping rows-as-objects/hashes (rather than arrays).

All the queries I make are 'executes' _with_ parameters.  They work fine. 

Request: Can you reverse host and port in 'exports.createTCPClient = function(host, port)' so that it follows NodeJS convention of (port, host).  I realise that the normal use case favours the existing ordering, but consistency across NodeJS is more important.  This ordering has cost me several hours in debugging (I now have a wrapper which does the reversing).  This issue may disappear completely if you switch to using an 'options argument' form of createClient.

Thanks,

Chris.

P.S. I'm now getting into transactions/InnoDB so I may come up with more requests or find some more issues.

My email is cmsdew@gmail.com if you want to take this discussion off-line.
