### ISSUE TITLE
Query finished event

### ISSUE THREAD

**Issue by mish15** [sidorares/nodejs-mysql-native#45]
When executing a db.query function and reading by rows, it's not easy to tell when the query is finished. If you're loading row by row and other executions are waiting on the loading to be complete, then that is an issue. I edited query.js to emit an event when it is complete, now i can load row by row, but still emit an event when the rows are done, see: this.emit("finished"); I think it's a pretty useful event to add. Thanks.

``` javascript
data: function( r )
    {
        if (r.isEOFpacket())
        {
            var eof = r.readOKpacket();
            if (eof.server_status & 8) // SERVER_MORE_RESULTS_EXISTS
            {
                return 'rs_ok';
            }
            this.emit('finished');
            return 'done';
        }
```

**Comment by sidorares** [comment]
need to double check, but I think all commands emit 'end' event at the end, should be equivalent to your 'finished' event

**Comment by mish15** [comment]
Ah, indeed you are right. Worth noting in the readme (where you list the supported events) i think. Many thanks, great package.

**Comment by sidorares** [comment]
first line in 'client functions' documentation - "All commands fire 'end'() event at the end of command executing."

But you're right, docs are old and ugly
