### ISSUE TITLE
Result as array of Objects [feature request]

### ISSUE THREAD

**Issue by Dunadan** [sidorares/nodejs-mysql-native#47]
My own bicycle for handy resultset, where builder is mysql.query(...), cb - callback.

function mysql_result(builder, cb)
    {
         var field_template = new Array;
         var results        = new Array;

```
      builder
          .on('field', function(f) { field_template[field_template.length] = f.name; }) 
          .on('row', function(r) {   

              var m = new Object;

              for(key in r)
              {
                 value = r[key];
                 m[field_template[key]] = value;
              }

              results.push(m);
          }) 
          .on('end', function() { cb(results) });
}
```

**Comment by sidorares** [comment]
this is built in from beginning ( see cmd.prototype.store_column in lib/command.js )
I'll probably keep array of fields API for 'row' event and array of Objects for high level callback in query(sql, callback)
