### ISSUE TITLE
Problem with SUM in mysql query

### ISSUE THREAD

**Issue by gotha** [sidorares/nodejs-mysql-native#49]
Hi, I don`t know if it is a bug or I`m doing something wrong.
Here is my code:

var db = require("mysql-native").createTCPClient();
db.auto_prepare = true;
db.auth("database", "user", "pass");

If I try to execute this:
var res = db.query(" SELECT id FROM users WHERE x = 'y' ");
everything is ok, but if I try 
var res = db.query(" SELECT SUM(id) FROM users WHERE x = 'y' ");
there is an error such as: 

.......\mysql-native\lib\mysql-native\commands\query.js:94
    return type_parsers[t](str, t);
                         ^
TypeError: Property '246' of object #<Object> is not a function

These queries are made up, but should give you the main idea. The sql queries are valid and execute properly, when executed  manualy through mysql client.

So .. is it a bug or a noob ? :)

**Comment by sidorares** [comment]
'SUM()' field type is MYSQL_TYPE_NEWDECIMAL which was not supported until recently ( fixed with #48 )
I opened #50 for better error handling in similar problems.

Solution for you - update library

**Comment by gotha** [comment]
thank you for the reply.
