### ISSUE TITLE
Date handling

### ISSUE THREAD

**Issue by sdepold** [sidorares/nodejs-mysql-native#5]
Hey guys...
The lib currently can't read dates from mysql. When do u expect to implement that feature?
Thanks a lot
sdepold

**Comment by sidorares** [comment]
At the moment you can get columns in the date format using query() ( serialised as string ).   Could you provide example test case (create table, update using query(), execute statement which shuld return date object) and i'll try to add binary row-> date serialisation

**Comment by sdepold** [comment]
I'm doing this:

var connection = require(__dirname+"/lib/nodejs-mysql-native/client").createTCPClient()
      connection.auto_prepare = true
      connection.auth('sequelize_test', 'test', 'test')
      connection
        .execute('SELECT \* FROM HelloWorlds')
        .addListener('row', function(r){
          SequelizeHelper.log(r)
        })
      connection.close()

the result is:
[ 1
, 'foo'
, '_not_implemented_ MYSQL_TYPE_DATETIME \'\u0000\u0000\u0001\u0000\u0000\u0000\u0003foo\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\''
, '_not_implemented_ MYSQL_TYPE_DATETIME \'\u0000\u0000\u0001\u0000\u0000\u0000\u0003foo\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\''
, '_not_implemented_ MYSQL_TYPE_DATETIME \'\u0000\u0000\u0001\u0000\u0000\u0000\u0003foo\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\u0007\u00da\u0007\b\u0006\u000b\u0017\u0004\''
]

what am i doing wrong?

**Comment by sdepold** [comment]
mhhh accidently closed the issue ...

**Comment by sdepold** [comment]
hey i tried using the query method and with it dates are working ^^
 nice nice

**Comment by sidorares** [comment]
should work now with commit 4bb459cf0b3d80282942

could you try your example query ( using execute() ) with this commit?

**Comment by sdepold** [comment]
Still pretty strange behavior :)

First of all, this is my table structure:
id:int; name:varchar; foo:datetime;  long_text: text; createdAt:datetime, updatedAt:datetime

And I have one entry:
id:1, name:foo, foo: 2010-08-11 16:53:16, long_text:asd, createdAt=updatedAt: 2010-08-11 16:53:16

Doing 
var connection = require(__dirname+"/lib/nodejs-mysql-native/client").createTCPClient()
      connection.auto_prepare = true
      connection.auth('sequelize_test', 'test', 'test')
      connection
        .query('SELECT \* FROM HelloWorlds')
        .addListener('row', function(r){
          SequelizeHelper.log(r)
        })
      connection.close()

renders the correct result for all non-datetime entries and returns for datetimes the current time (new Date()). Taking a look into the code I found in commands.js#19 parseTime which always returns new Date()

Using execute returns the following:
[ 50331648
, 'oo\u0007\u00da\u0007\b\u000b\u00105\u0010\u0003asd\u0007\u00da\u0007\b\u000b\u00105\u0010\u0007\u00da\u0007\b\u000b\u00105\u0010'
, Invalid Date
, ''
, Invalid Date
, Invalid Date
]

**Comment by sidorares** [comment]
oops, date output for text packet ( query() ) is not working, indeed.
parseTime shoud transform string representetion of date (in mysql notation) into Date object. I'll tru to fix parseTime soon.

binary packet deserialisation is at serialisers.js reader.prototype.unpackBinaryTime/Date/DateTime functions ( Invalid Date created there )

**Comment by sdepold** [comment]
any progress on that?

**Comment by sidorares** [comment]
should be fixed in 59a07ac67339b7381fd1
both regular query() and prepared stmt execute() should work correctly with dates. Note that query() does not interpret date and return string from the result as is, while for binary packet result is converted to javascript Date object. (same for null result - empty string for query() and js null for execute)
