### ISSUE TITLE
About Asynchronous

### ISSUE THREAD

**Issue by bobchennan** [sidorares/nodejs-mysql-native#59]
Is it possible when I code like this:
<code>db.query("use one");
db.query("select \* from ...");
</code>
and another place:
<code>db.query("use two");
db.query("select \* from ...");
</code>
there will be some mistakes about asynchronous?

**Comment by sidorares** [comment]
`db.commandname` is `put command to db manager queue`. Since next command is dequeued only after previous finished it's completely safe to use code like

```
 db.query('use db1');
 db.query('select sleep(1)');
 db.query('use db2');
 console.log('ok');
```

all queries are executed in order here (but 'ok' is printed even before 'use db1' is executed)

**Comment by bobchennan** [comment]
But if I code like this:
app.get('/test1',function(){
    db.use('two');
    db.query('...');
});
app.get('/test2',function(){
    db.use('one');
    db.query('...');
});

And two users visit test1 and test2 at the same time,what will happen?

2012/3/1 Andrey Sidorov <
reply@reply.github.com

> `db.commandname` is `put command to db manager queue`. Since next command
> is dequeued only after previous finished it's completely safe to use code
> like
> 
> ```
> db.query('use db1');
> db.query('select sleep(1)');
> db.query('use db2');
> console.log('ok');
> ```
> 
> all queries are executed in order here (but 'ok' is printed even before
> 'use db1' is executed)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/sidorares/nodejs-mysql-native/issues/59#issuecomment-4248882

## 

QQ:404692150

**Comment by sidorares** [comment]
because 'put command to queue' is non-io, blocking task (it's just sequence of serial JS commands) server won't process second handler until first is processed

```
app.get('/test1',function(req, res){
    db.query('use one');
    db.query('select sleep(1)');
    db.query('select sleep(1)').on('end', function() {
        res.send('test1');
    });
});

app.get('/test2',function(req, res){
     db.query('select sleep(1.5)');
     db.query('use two');
     db.query('select sleep(1)').on('end', function() {
         res.send('test1');
     });
 });
```

now, if you have request /test1 and 0.1 sec later '/test2' both get handlers will exit almost immediately and you'll have this db queue:

```
  use one;
  select sleep(1);
  select sleep(1);  // here /test1 handler
  select sleep(1.5);
  use two;
  select sleep(1); // here /test2  handler
```

You'll see /test1 response in approx 2 seconds and /test2 in approx 4.5-0.1 seconds from the moment each request issued, respectively.

**Comment by bobchennan** [comment]
I see, thanks a lot.

2012/3/1 Andrey Sidorov <
reply@reply.github.com

> because 'put command to queue' is non-io, blocking task (it's just
> sequence of serial JS commands) server won't process second handler until
> first is processed
> 
>    app.get('/test1',function(req, res){
>        db.query('use one');
>        db.query('select sleep(1)');
>        db.query('select sleep(1)').on('end', function() {
>            res.send('test1');
>        });
>    });
> 
>    app.get('/test2',function(req, res){
>         db.query('select sleep(1.5)');
>         db.query('use two');
>         db.query('select sleep(1)').on('end', function() {
>             res.send('test1');
>         });
>     });
> 
> now, if you have request /test1 and 0.1 sec later '/test2' both get
> handlers will exit almost immediately and you'll have this db queue:
> 
> ```
>  use one;
>  select sleep(1);
>  select sleep(1);  // here /test1 handler
>  select sleep(1.5);
>  use two;
>  select sleep(1); // here /test2  handler
> ```
> 
> You'll see /test1 response in approx 2 seconds and /test2 in approx
> 4.5-0.1 seconds from the moment each request issued, respectively.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/sidorares/nodejs-mysql-native/issues/59#issuecomment-4252282

## 

QQ:404692150
