### ISSUE TITLE
about execute

### ISSUE THREAD

**Issue by bobchennan** [sidorares/nodejs-mysql-native#61]
How can I use (?) in execute?

I just write like that:

```
db.execute('UPDATE '+config.userTableName+' SET (?) = (?) WHERE name= (?)',[escape(key),escape(value),escape(user)]);
```

But it's failed. There are two types: one is normal and the other needs to add "" to indicate it's a string in mysql. How can I write it using (?)?

**Comment by sidorares** [comment]
can you provide complete working example? 
you don't need to add quotation or escape string parameters - see example:

```
 // numbers
 db.execute('select ?+?', [2, 3]).on('end', function(r) { console.log(r.result.rows) });     
 // strings
 db.execute('select concat(?,",",?)', ['hello', 'world']).on('end', function(r) { console.log(r.result.rows) });
```

**Comment by bobchennan** [comment]
How about

```
     var result = db.execute('SELECT * FROM ' + config.userTableName + ' WHERE name=(?)', [escape(username)]);
```

config.userTableName is  name of one table. How can I write it using parameters?

**Comment by sidorares** [comment]
http://dev.mysql.com/doc/refman/5.0/en/prepare.html
you cannot use place holders or SQL keywords, identifiers, and so forth

in your example you should use something like

```
db.execute('SELECT * FROM ' + escape(config.userTableName) + ' WHERE name=?', [username]);
```

**Comment by bobchennan** [comment]
Thanks a lot
 2012-4-2 2:01"Andrey Sidorov" <
reply@reply.github.com
