### ISSUE TITLE
crash when handling texts

### ISSUE THREAD

**Issue by sdepold** [sidorares/nodejs-mysql-native#7]
Hey there,

I think I found a bug.
When using a table with varchar(>255) or text the select query crashes at commands.js 264:
    /Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:266
                    var value = string2type(r.lcstring(), field.type); // todo: mo
                                                               ^
    TypeError: Cannot read property 'type' of undefined
        at cmd.data (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:266:60)
        at cmd.process_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:144:43)
        at [object Object].dispatch_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:115:37)
        at Stream.<anonymous> (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:161:28)
        at Stream.emit (events:26:26)
        at IOWatcher.callback (net:507:33)
        at node.js:267:9

You seem to expect that every column has the same 'length', so that every iteration of while (!r.eof()) is excactly one column. This seems to be not the case if columns are 'longer' than 255 chars.

Any idea how and when you fix this?

**Comment by sidorares** [comment]
could you provide query, "SHOW CREATE TABLE" and fields meta dump for your example?
For some reason fields array is smaller than row data (which I believe should not happen regardless of column type)

to dump field description:
conn.query(q).addListener('field', function(f) { sys.puts( sys.inspect(f) ); } );

Also example output for this table and query using regular mysql console client would help

**Comment by sdepold** [comment]
First of all, this is my table structure:
id:int; name:varchar; foo:datetime; long_text: text; createdAt:datetime, updatedAt:datetime

I created an entry with long_text = 'lorem ipsum lorem ipsum...' (2600 characters long ;))

what do you mean with show create table. what do i have to do ?

**Comment by sidorares** [comment]
http://dev.mysql.com/doc/refman/5.0/en/show-create-table.html

**Comment by sdepold** [comment]
ah ic:

node test.js 
'Executing the query: DROP TABLE IF EXISTS HelloWorlds'
'Executing the query: CREATE TABLE IF NOT EXISTS HelloWorlds (id INT NOT NULL auto_increment PRIMARY KEY, name VARCHAR(255), foo DATETIME, long_text TEXT, createdAt DATETIME NOT NULL, updatedAt DATETIME NOT NULL)'
{ catalog: 'def'
, db: ''
, table: ''
, org_table: ''
, name: 'Table'
, org_name: ''
, filler: 0
, charsetnum: 8
, length: 64
, type: 253
, flags: 1
, decimals: 31
, defval: ''
}
{ catalog: 'def'
, db: ''
, table: ''
, org_table: ''
, name: 'Create Table'
, org_name: ''
, filler: 0
, charsetnum: 8
, length: 1024
, type: 253
, flags: 1
, decimals: 31
, defval: ''
}

/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:264
                var value = string2type(r.lcstring(), field.type); // todo: mo
                                                           ^
TypeError: Cannot read property 'type' of undefined
    at cmd.data (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:264:60)
    at cmd.process_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/commands.js:144:43)
    at [object Object].dispatch_packet (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:115:37)
    at Stream.<anonymous> (/Users/prototype/Projects/sequelize/lib/nodejs-mysql-native/client.js:161:28)
    at Stream.emit (events:26:26)
    at IOWatcher.callback (net:507:33)
    at node.js:267:9

**Comment by sdepold** [comment]
code:

HelloWorld.drop(function() {
  HelloWorld.sync(function() {
    var connection = require(__dirname+"/lib/nodejs-mysql-native/client").createTCPClient()
    connection.auto_prepare = true
    connection.auth('sequelize_test', 'test', 'test')
    connection
      .query('SHOW CREATE TABLE HelloWorlds')
      .addListener('field', function(r){
        SequelizeHelper.log(r)
      })
    connection.close()  
  })
})

**Comment by sidorares** [comment]
length-coded number reader implementation was incomplete ( see commit f1439724740c53413946 ). Thanks for report.

**Comment by sdepold** [comment]
works perfectly :)
