### ISSUE TITLE
SQL injection?

### ISSUE THREAD

**Issue by ghost** [sidorares/nodejs-mysql-native#72]
I couldn't find any readily available documentation about whether or not this library does even basic protection from SQL injection. I would assume it does, but just want to double check as this is a pretty basic security requirement.

**Comment by sidorares** [comment]
IMHO preventing sql injection is responsibility of driver user. On the driver side I promote usage of prepared statements `db.execute("select * from t where i=?", [j])` to client-side interpolated `db.query("select *from t wehere i='" + j + "'")`. In the case of `execute` parameters are separated from query string on the wire protocol level.
