### ISSUE TITLE
Transactions Not Supported via execute(); Only via query()

### ISSUE THREAD

**Issue by gilbo** [sidorares/nodejs-mysql-native#73]
I got the following error message when trying to issue a "START TRANSACTION" command via execute():

```
Error: This command is not supported in the prepared statement protocol yet
```

Using a query solved the problem.

Is this an issue with the driver being incomplete, or are you just reflecting the state of affairs beneath you?

**Comment by sidorares** [comment]
It's server limitation and error message is from server, not driver:

http://forums.mysql.com/read.php?20,4976,5011#msg-5011 :

Prepared statements are restricted to only a few category of statements. The type of queries that they work on is limited to DML (INSERT, REPLACE, UPDATE, and DELETE), CREATE TABLE, and SELECT queries. Support for additional query types will be added in further versions, to make the prepared statements API more general.
