### ISSUE TITLE
global leak of 'h'

### ISSUE THREAD

**Issue by chrisdew** [sidorares/nodejs-mysql-native#75]
I'm trying to use mysql-native with mocha.

Mocha detects global leaks - e.g.

```
h = 42; // when 'h' has not been declared
```

instead of

```
var h = 42;
```

A typical error is:

```
1) The engine module "before each" hook:
Error: global leak detected: h
```

The error always involves 'h'.  Does mysql-native use an 'h' without declaring it?

**Comment by sidorares** [comment]
Hard to remember. Easiest way to spot global variable leak is to add property setter, like

``` js
global.__defineSetter__('h', function() {
   console.log('property h leak!');
   console.trace();
})
```
