### ISSUE TITLE
getting id of inserted entries?

### ISSUE THREAD

**Issue by sdepold** [sidorares/nodejs-mysql-native#8]
Is there a way I can execute an insert query and get the id of the new entry in return? or do I have to make a select query after that?

**Comment by sidorares** [comment]
before commit  b0bdb3809bac45d630e7 the only possibility was "SELECT LAST_INSERT_ID()"

insert_id is now set in query() or execute() command

example:
conn.execute("INSERT INTO test VALUES(1,2,3)").on('end', function() { sys.puts("insert id:" + this.insert_id); });

please let me know if inert_id is working correctly

**Comment by itunali** [comment]
please add same feature with "affected_rows" for updated or deleted rows, thanks

**Comment by sidorares** [comment]
done

**Comment by itunali** [comment]
thanks a lot. I hope you will get some improvements to pooling.

**Comment by sdepold** [comment]
hmm how do u do it??? my code:

var connection = require("/Users/prototype/Projects/nodejs-mysql-native/mysql/client").createTCPClient()
    connection.auto_prepare = true
    connection.auth('sequelize_test', 'test', 'test')
    connection.execute("INSERT INTO HelloWorlds (name, foo, long_text, createdAt, updatedAt) VALUES ('hello',NULL,NULL,'2010-08-12 20:00:41','2010-08-12 20:00:41')").on('end', function() { require("sys").puts("insert id:" + this.insert_id); })
    connection.close()

this prints:insert id:undefined

**Comment by sdepold** [comment]
hmm how do u do it??? my code:

var connection = require("/Users/prototype/Projects/nodejs-mysql-native/mysql/client").createTCPClient()
    connection.auto_prepare = true
    connection.auth('sequelize_test', 'test', 'test')
    connection.execute("INSERT INTO HelloWorlds (name, foo, long_text, createdAt, updatedAt) VALUES ('hello',NULL,NULL,'2010-08-12 20:00:41','2010-08-12 20:00:41')").on('end', function() { require("sys").puts("insert id:" + this.insert_id); })
    connection.close()

this prints:insert id:undefined

**Comment by itunali** [comment]
get stats via callback argument.

<pre>.on('end', function(stats) { require("sys").puts("insert id:" + stats.insert_id); })</pre>

**Comment by sidorares** [comment]
yes, thanks

**Comment by sdepold** [comment]
works like a charm :) thanks a lot
